"""add milestone_roadmap_items

Revision ID: 936302d43b50
Revises: 8d6720d5a933
Create Date: 2026-09-07 21:02:15.982499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936302d43b50'
down_revision: Union[str, None] = '8d6720d5a933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_roadmap_items',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('roadmap_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roadmap_item_id'], ['roadmap_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('milestone_id', 'roadmap_item_id')
    )
    op.drop_constraint(op.f('roadmap_items_parent_id_fkey'), 'roadmap_items', type_='foreignkey')
    op.create_foreign_key(None, 'roadmap_items', 'roadmap_items', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmap_items', type_='foreignkey')
    op.create_foreign_key(op.f('roadmap_items_parent_id_fkey'), 'roadmap_items', 'roadmap_items', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_table('milestone_roadmap_items')
    # ### end Alembic commands ###
